### ISSUE TITLE
Binaries

### ISSUE THREAD

**Issue by Gusher** [Snowapril/Procedural-Terrain-Estimator#26]
You have binaries for install or instructions?

**Comment by Snowapril** [comment]
Hello :)
executable file and related resources were registered at Release tab.
Check out below link.
[Release](https://github.com/Snowapril/Procedural-Terrain-Estimator/releases/tag/1.1.0)

I have plan to refactor whole proejct architecture for making enable to build project with CMake. 
Thank you

**Comment by Gusher** [comment]
Thank you very much!
